###
GET http://localhost:5000/auth/refresh

###
DELETE http://localhost:5000/auth/logout

###
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "username":"siswa",
    "password":"siswa"
}

###
POST http://localhost:5000/siswa/add-profil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9ha3VuIjoyMiwidXNlcm5hbWUiOiJzaXN3YTEiLCJyb2xlIjoic2lzd2EiLCJpYXQiOjE2NTI4MDM0NjcsImV4cCI6MTY1MjgyNTA2N30.0zOAwr0nQvw6dYCIq2k_tvfHKl-hnrI2Dj7rLo2i4-c
Content-Type: application/json

{
    "namaSiswa":"ciri"
}

###
GET http://localhost:5000/siswa/get-profil
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNpc3dhMSIsImlhdCI6MTY1Mjg2Njg2NywiZXhwIjoxNjUyODg4NDY3fQ.Z-YsDWUO1Vi3U2mGWHoNMDo1LDWnG9_gMCYb3tDGjbw


###
POST http://localhost:5000/course/join
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9ha3VuIjozMywidXNlcm5hbWUiOiJzaXN3YSIsInJvbGUiOiJzaXN3YSIsImlzTmV3Ijoibm8iLCJpYXQiOjE2NTMyNTAzNjgsImV4cCI6MTY1MzI1MDM4OH0.SVGMkQXP1x-gqhbJlIzaBdKLH34jhlD2hD8Md3J4mNg
Content-Type: application/json

{
    "idcourse":"9"
}

###
POST http://localhost:5000/course/verify-answer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNpc3dhIiwicm9sZSI6InNpc3dhIiwiaXNOZXciOiJubyIsImlhdCI6MTY1MzMxMTUyNCwiZXhwIjoxNjUzMzExNTQ0fQ.1kKy3Fvl-BmZNKvfmPDxOfWpldq2wVs1FxWZ5l-pVH8
Content-Type: application/json

{
    "jawaban":[ 
        {
            "idSoal":"14",
            "answer":"option_b"
        },
        {
            "idSoal":"16",
            "answer":"option_d"
        }
    ],
    "idexercise":"27"

}

###
POST http://localhost:5000/siswa/level-up
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9ha3VuIjoyMiwidXNlcm5hbWUiOiJzaXN3YTEiLCJyb2xlIjoic2lzd2EiLCJpYXQiOjE2NTI4MDQ1MTQsImV4cCI6MTY1MjgyNjExNH0.BaAeyWmzekRUd9PVFpqG72PtKcWsi_AYn0hqj1ZYn9Y
Content-Type: application/json

{
    "pointSiswa":"200"

}

###
//jointbadges
POST http://localhost:5000/siswa/add-badges
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNpc3dhIiwicm9sZSI6InNpc3dhIiwiaXNOZXciOiJubyIsImlhdCI6MTY1MzMxMTMzOSwiZXhwIjoxNjUzMzExMzU5fQ.eVnMXP_djlLFD25584-TGu9sqsvJynXGUb7TXEachUk
Content-Type: application/json

{
    "idProfil":"13",
    "pointSiswa":"200",
    "materiFinished":"1",
    "exerciseFinished":"1"

}

###
//materiverify & joint
POST http://localhost:5000/course/verify-materi
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9ha3VuIjoyMiwidXNlcm5hbWUiOiJzaXN3YTEiLCJyb2xlIjoic2lzd2EiLCJpYXQiOjE2NTI4NTg4NzYsImV4cCI6MTY1Mjg4MDQ3Nn0.eVPUsNrZCsADnyrSX6z2KiYKzbvjqCrWamiWlEGvWfw
Content-Type: application/json

{
    "idMateri":"8"
  
}


###
GET http://localhost:5000/course/get-course/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNpc3dhMSIsInJvbGUiOiJzaXN3YSIsImlzTmV3Ijoibm8iLCJpYXQiOjE2NTMxMjcyODcsImV4cCI6MTY1MzEyNzMwN30.JpS6v739p4GkDwms80yb61p_ul2keiDeP7ZQEtNBeQg

###
GET http://localhost:5000/course/get-course-exercise/soal
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZF9ha3VuIjoyMiwidXNlcm5hbWUiOiJzaXN3YTEiLCJyb2xlIjoic2lzd2EiLCJpc05ldyI6Im5vIiwiaWF0IjoxNjUzMDUyMjA4LCJleHAiOjE2NTMwNTIyMjh9.3lBZYvDEJSVasqXUmAyWW_DrdZaBHHbXOleMlJLFrHI
Content-Type: application/json

{
    "idExercise":"9"
}

###
GET http://localhost:5000/course/get-course-materi-detail/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNpc3dhIiwicm9sZSI6InNpc3dhIiwiaXNOZXciOiJubyIsImlhdCI6MTY1MzIzMzA0NCwiZXhwIjoxNjUzMjMzMDY0fQ.cw2HzNEsR8y_NcNFtj5J7Doboh3290pNu08pbI0CX5w
